### ISSUE TITLE
When? How?

### ISSUE THREAD

**Issue by TheEpicTen** [Fabrizz/MMM-LiveLyrics#1]
How do I get this module? Or do I have to wait?

No download instructions in the README...

**Comment by Fabrizz** [comment]
Hey, as said in the OnSpotify issue, im rewriting the module. If I have time you can install it this week. If not maybe 2 3 more weeks as I have stuff to do. You can use the watch button. (Im going to post on reddit/the MM2 discord when its available)

**Comment by Fabrizz** [comment]
![Group 402](https://user-images.githubusercontent.com/65259076/227824049-45feb4e7-fa9f-4f70-bd55-0f0811b9fe50.png)

Im finishing the development!, any feature that you would like to see in the module?

**Comment by TheEpicTen** [comment]
Can there be a feature to make it only show sometimes? Like when the music is playing.

**Comment by Fabrizz** [comment]
I had forgotten about that, im going to add it! thanks

**Comment by HasseM** [comment]
I'm using MM2 on a 7" RPi screen in landscape. So rather small. It is not even a mirror but just a screen showing info and when spotyfi is playing, I want it to display the artwork and titel. Additionally I would like it to scroll the lyrics on it. But space for it is rather limited on this small display. So combine artwork, titel and lyrics in a readable manner.

I hope you consider features for small screens in landscape mode!

Let me know if you need someone for testing and feedback!

**Comment by Fabrizz** [comment]
> I'm using MM2 on a 7" RPi screen in landscape. So rather small. It is not even a mirror but just a screen showing info and when spotyfi is playing, I want it to display the artwork and titel. Additionally I would like it to scroll the lyrics on it. But space for it is rather limited on this small display. So combine artwork, titel and lyrics in a readable manner.
> 
> I hope you consider features for small screens in landscape mode!
> 
> Let me know if you need someone for testing and feedback!

Yeah, there is going to be a style that uses the full screen and does not use a separated container, when in landscape mode the horizontal "NowPlaying" bar changes to a vertical player-like container.

Also there is going to be documentation on what CSS to change to have one effect or another.

About testing, in a couple of days im going to update OnSpotify to the 2.0V so it works with this module, after that im probably going to put a working code on the dev branch

**Comment by Fabrizz** [comment]
@HasseM @TheEpicTen Its finished! Im about to post in discord/reddit, if any of you want, take a look to see if it works on your devices!

**Comment by HasseM** [comment]
Hi, I'm testing it now on the RPi official 7" touchscreen (horizontally).

![image](https://user-images.githubusercontent.com/7515641/231161157-d707eccf-5e6c-4e43-ac13-4ec67143cdc1.png)

As you can see, the right side album art is not as it should be.

Also I am experiencing a problem with the lyrics text not scrolling. My config is like:

				// Module behaviour [See below]
				useDefaultSearchFormatter: true,
				useMultipleArtistInSearch: true,
				logSuspendResume: false,
				showConnectionQrOnLoad: false,
				connectionQrDuration: 12,
				sideBySideOnLandscape: true,
				startHidden: false,
				hideSpotifyModule: true,
				updateTopModulesCalcOnData: true,
				// Lyrics style [See below]
				lyricsFillType: "full",
				lyricsContainerBackdropStyle: "black",
				lyricsStyleTheme: "dynamicblobsFull",
				lyricsFontName: null,
				lyricsFontSize: null,
				lyricsTextAlign: null,
				lyricsCustomFixedDimentions: false,
				// Scroll and others [See below]
				scrollStrategy: "byAnimationFrame",
				scrollUpdateEvery: 3,
				hideStrategy: "flex",
				blurToBlackOnFull: false,
				useAnimations: true,

**Comment by TheEpicTen** [comment]
Have you made the update for OnSpotify?

**Comment by TheEpicTen** [comment]
Can't connect to mm from phone. This is my IP related config. What is wrong?

`let config = {
	address: "::", 	// Address to listen on, can be:
							// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
							// - another specific IPv4/6 to listen on a specific interface
							// - "0.0.0.0", "::" to listen on any interface
							// Default, when address config is left out or empty, is "localhost"
	port: 8080,
	basePath: "/", 	// The URL path where MagicMirror² is hosted. If you are using a Reverse proxy
					// you must set the sub path here. basePath must end with a /
	**ipWhitelist: [], 	// Set [] to allow all IP addresses**`

**Comment by HasseM** [comment]
> Have you made the update for OnSpotify?

well, that fixed the scrolling!

So' it's just the album art not being 100%

**Comment by HasseM** [comment]
So, when the music is paused, the lyrics scrolling is not paused?

**Comment by Fabrizz** [comment]
> > Have you made the update for OnSpotify?
> 
> well, that fixed the scrolling!
> 
> So' it's just the album art not being 100%

I had forgotten to push the fix for MMM-OnSpotify.

I'm going to put some media queries for lower PPI devices. If you want to be perfect for your display I would suggets to use custom font-size values usign ems, that way It look and is aligned perfectly

Also, can you send you display resolution?

**Comment by Fabrizz** [comment]
> Can't connect to mm from phone. This is my IP related config. What is wrong?
> 
> `let config = {
> 	address: "::", 	// Address to listen on, can be:
> 							// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
> 							// - another specific IPv4/6 to listen on a specific interface
> 							// - "0.0.0.0", "::" to listen on any interface
> 							// Default, when address config is left out or empty, is "localhost"
> 	port: 8080,
> 	basePath: "/", 	// The URL path where MagicMirror² is hosted. If you are using a Reverse proxy
> 					// you must set the sub path here. basePath must end with a /
> 	**ipWhitelist: [], 	// Set [] to allow all IP addresses**`

I cant view the code due to formatting.
Is `ipWhitelist` set to `[]`?
~~`address` needs to be `0.0.0.0` so it listens on every interface~~ (`::` is ok)

**Comment by HasseM** [comment]
> > > Have you made the update for OnSpotify?
> > 
> > 
> > well, that fixed the scrolling!
> > So' it's just the album art not being 100%
> 
> I had forgotten to push the fix for MMM-OnSpotify.
> 
> I'm going to put some media queries for lower PPI devices. If you want to be perfect for your display I would suggets to use custom font-size values usign ems, that way It look and is aligned perfectly
> 
> Also, can you send you display resolution?

It's this screen: https://www.raspberrypi.com/products/raspberry-pi-touch-display/

So, it's 800x480.

My use-case is information screen. When music is playing, I want it to show what's playing and lrics would be a cool addition. I have also a DAC on it (Hifiberry). When no music is playing, it just displays some other MM things.

**Comment by TheEpicTen** [comment]
How do I update? If it's just git pull, i get this error
error: The following untracked working tree files would be overwritten by merge:
	.github/content/banner-livelyrics.png
Please move or remove them before you merge.
Aborting

**Comment by TheEpicTen** [comment]
So. I've got the module. When I press Ctrl+R, the module flashes for a second and then disappears. The OnSpotify module isn't hiding, so presumably it doesn't think it's playing anything, but it knows it is, because it is showing the lyrics in the remote. What is the problem?

Edit: Solved. The problem is that OnSpotify isn't updated, but there is an error when I use git pull. Error is:

error: The following untracked working tree files would be overwritten by merge:
            .GitHub/content/banner-livelyrics.png
Please move or remove them before you merge.
Aborting






What does this mean and how do I fix it?

**Comment by Fabrizz** [comment]
> So, when the music is paused, the lyrics scrolling is not paused?

In the one that uses animationFrame? I can add it as a toggle maybe, in now doing the screen stuff

**Comment by Fabrizz** [comment]
> So. I've got the module. When I press Ctrl+R, the module flashes for a second and then disappears. The OnSpotify module isn't hiding, so presumably it doesn't think it's playing anything, but it knows it is, because it is showing the lyrics in the remote. What is the problem?
> 
> Edit: Solved. The problem is that OnSpotify isn't updated, but there is an error when I use git pull. Error is:
> 
> error: The following untracked working tree files would be overwritten by merge: .GitHub/content/banner-livelyrics.png Please move or remove them before you merge. Aborting
> 
> What does this mean and how do I fix it?

Did you changed anything on your local machine? You can force pull, it does not matter. Is the suff related to OnSpotofy now working?

**Comment by TheEpicTen** [comment]
I fixed everything now, thanks.
