### ISSUE TITLE
Lyrics Not Found

### ISSUE THREAD

**Issue by P16gxx** [Fabrizz/MMM-LiveLyrics#10]
Module is showing no Lyrics found.
Have checked token, and when blank, sits on "Searching for Token"
MMM-OnSpotify is sending out notifications as this is being picked up by another modules,

**Comment by melon-1999** [comment]
I have the same problem

**Comment by Fabrizz** [comment]
It seems that Genius changed something on their end. Will look into this

**Comment by Fabrizz** [comment]
Fixed! Genius made some layout changes. If it works/dont let me know!
