### ISSUE TITLE
Can you make it so that it can exclude the left modules

### ISSUE THREAD

**Issue by TheEpicTen** [Fabrizz/MMM-LiveLyrics#3]
Like fullCalcTopModules, but fullCalcLeftModules

**Comment by Fabrizz** [comment]
When I finish with the smaller screens and some people reporting the module as not interactive, I will do it
(you can do that for now by changing `getTopModulesHeight` in `LyricsDomBuilder.js` and changing the CSS calcs as the ones from the top modules)
