### ISSUE TITLE
Hi. I have a question.

### ISSUE THREAD

**Issue by TheEpicTen** [Fabrizz/MMM-LiveLyrics#4]
So, theres an API for showing/hiding the lyrics right? Is there a way we can integrate that with Amazon Alexa to show and hide the modules?

**Comment by Fabrizz** [comment]
### You can use the following endpoints:
![image](https://user-images.githubusercontent.com/65259076/235538139-2b81a092-0134-45e3-8e38-4ec1efcb8c3a.png)

### or you can use the included module notifications from other modules that allow you to use alexa:
`LYRICS_TOGGLE` `LYRICS_SHOW` `LYRICS_HIDE`


edit: you can use other modules that expose internal notification as amazon compatibld lights or use external services like home assistant or similar
