### ISSUE TITLE
Adapting scrolling to other input/div

### ISSUE THREAD

**Issue by Cam9731** [Fabrizz/MMM-LiveLyrics#9]
Hello,

I've recently been working on adapting your module to be compatible with Plex, which is the main way that I listen to music. I've got most of the functionality working, but I can't find a way to switch between divs for monitoring where in the lyrics I am.

Currently, scrolling is done by monitoring the div stored in the PLAYERPROGRESS variable.  I tried conditionally modifying this variable such that when music is playing from plex, it uses my data to determine the percentage, but when music is playing through Spotify, it behaves as it currently does but didn't seem to have any luck. I want the module to work for both Spotify and Plex, and this is the last puzzle piece haha.

I played around a bit with modifying the scroller_bySections() function but didn't have a ton of luck as a lot of it is set in constants that didn't take kindly to modifying.

I already have all the percentage calculations done for Plex, I just need a way to have the module scroll like it does for Spotify.

Thanks for any suggestions you might have (And the great module)!

**Comment by Fabrizz** [comment]
Do you have this in a repository? So I can take a look at it, I guess that your plex module is sending a `NOW PLAYING` notification and the module just thinks that its MMM-OnSpotify

What I would do is add to the notification object an entry like
```
{
    [...]
    player: "MMM-yourPlexModule"
    targetTimeDiv: "divId"
}
```

And just change MMM-LiveLyrics saved reference to the div. 

Im going to comment again, but I think that this module references a `data=""` param in html, not the content by itself

**Comment by Fabrizz** [comment]
```js
const max = parseInt(extProgress.getAttribute("max")) ?? 1;
const now = parseInt(extProgress.getAttribute("now")) ?? 1;
```

This are the two lines that get the timestamps for current/max time. (`extProgress` is the element), `.getAttribute("now")` means that it gets the data from an HTML attribute like this:
```html
<div class="..." id="ref" max="TIMESTAMP" now="TIMESTAMP" >1:17/4:23</div>
```

So your plex module should add a div with max and now attributes if you dont want to rebuild this part again

**Comment by Cam9731** [comment]
I figured it out. My initial method of going about this was really stupid (In my defense it was 4am haha) but I ended up conditionally setting the value of an element to have the timestamps of either plex or spotify depending on what I'm listening to at the time. 

I'll reply to this thread with my forked repo once I clean this up and push it through in case anyone in the future attempts something similar.

**Comment by Cam9731** [comment]
For reference and if anyone attempts something similar:

https://github.com/Cam9731/MMM-PlexNowPlaying
https://github.com/Cam9731/MMM-OnSpotify
https://github.com/Cam9731/MMM-LiveLyrics

Also @Fabrizz thanks for the quick response, I appreciate it!
